[package]
name = "Koban"
edition = "2024.beta"
published-at = "0x7b148e0fd4170eea84566ae1fb720a6ced17abbba4283e20f7fdad9cc8342760"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
koban = "0x7b148e0fd4170eea84566ae1fb720a6ced17abbba4283e20f7fdad9cc8342760"

[dev-dependencies]

[dev-addresses]

